export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const POST_VOTE_UP = 'POST_VOTE_UP'
export const POST_VOTE_DOWN = 'POST_VOTE_DOWN'
export const ADD_NEW_POST = 'ADD_NEW_POST'

export const COMMENT_VOTE_UP = 'COMMENT_VOTE_UP'
export const COMMENT_VOTE_DOWN = 'COMMENT_VOTE_DOWN'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'